export default function useMenuNames(){
     const OZCOM = 'OZCOM'
     const ACTIVITY_SERVICE = 'ACTIVITY_SERVICE'
     const INTERACTIVE_SERVICES = 'INTERACTIVE_SERVICES'
     const DOCUMENTS = 'DOCUMENTS'
     const REMIND = 'REMIND'
     const EVENTS = 'EVENTS'
     const INFORMATION_SERVICE = 'INFORMATION_SERVICE'
     const NETWORK = 'NETWORK'

    return {
        OZCOM,ACTIVITY_SERVICE,INTERACTIVE_SERVICES,DOCUMENTS,REMIND,EVENTS,INFORMATION_SERVICE,NETWORK
    }
}
